### PR TITLE
Hotfix/event aggregation auto subscription module handler cleanup

### PR DESCRIPTION
**Pull request by dittodhole**

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
Hi there. With my team we're just recently contributing to this project.

Would you mind describing the purpose/usefulness/need/xxx for this current PR? 
Thanks!

**Comment by dittodhole** [comment]
We currently introduced the creation of LifetimeScopes (http://docs.autofac.org/en/latest/lifetime/) to our WPF application upon resolving of ViewModels (Screens). This gives us the opportunity to release dependant registrations/resolving earlier (ie when the ViewModel is deactivated/closed) - way better than waiting for the root LifetimeScope to dispose.

The problem is, that the automatic subscription of `IHandle`-instances introduces a memory-leak here - imagine following situation:
- ViewModel A gets resolved
- Then `OnComponentActivated` kicks in and subscribes the instance for pubs of `IEventAggregator`
- ViewModel A gets closed
- Associated LifetimeScope gets disposed
- ViewModel A gets disposed (if implementing `IDisposable`), and any descendant resolved instances (dependency tree)
- ViewModel A is still connected with `IEventAggregator`

This is actually no big deal when working with the stock `EventAggregator` class, as it internally works with `WeakReferences` ...

Nevertheless, one can not guarantee the internal working of the actual aggregator, and _correct_ cleanup is nice :)

**Comment by BrainCrumbz** [comment]
Never tried this, but I was thinking about contributing by directly committing to your branch in your fork, so that changes would show up here. Don't know if that works though. Changes would be not-critical, like spacing and comments. 

On a related note, maybe `DisposableWrapper` could be named `DisposableAction`?

**Comment by dittodhole** [comment]
Rename as you wish :beers:

Actually, Caliburn.Micro internally has `Autofac.Util.ReleaseAction`, which is used to register the delegate of `registration.OnRelease`-calls ... declared as `internal` though

**Pull request merged**
