### PR TITLE
Fixes build

### PR DESCRIPTION
**Pull request by brendankowitz**
* Fixes appveyor build
* Publishes nuget when a there is a new commit to master branch

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
Re. _Publishes nuget when a there is a new commit to master branch_, that's interesting. Does that mean that now there should be some minimal policy for commiting to master?

**Comment by brendankowitz** [comment]
I would like to see everything go through a branch/PR before master, so I think master should be shipped, a pre-release nuget will be build on PRs and is available in the appveyor feed. 

We can change this, but I'd like to start with a lower barrier and faster turn-around for publishing updates

**Comment by BrainCrumbz** [comment]
Yeah, that makes sense. One thing though: usually not **all** changes go through a branch/PR, sometimes they're not big enough or "meaningful" enough for that. Yet they should not cause a new package release right away.
That sounds like some _dev_ branch should be used, where the "normal" development work happens, where PR are merged regularly, and then when you accrued enough work, you merge _dev_ to _master_ and you have a release.
Or, equivalent, you swap the two: you do most of development work on master and PRs are merged into master, then when you think are ready for a new release, you merge _master_ into some _release_ branch, and that gets shipped.
Thoughts?

**Comment by brendankowitz** [comment]
..how about we keep the creation of a nuget into the appveyor feed on each master merge, but push to nuget when that commit is tagged? I'm pretty sure it can be configured to do that

**Comment by BrainCrumbz** [comment]
👍 👍  sounds great

**Comment by BrainCrumbz** [comment]
Was looking for something else, and then found [this post](http://andrewlock.net/publishing-your-first-nuget-package-with-appveyor-and-myget/) with an `appveyor.yml` example showing how to publish to NuGet when master branch is tagged (search for _appveyor.yml_ within page). In case it might be helpful.

**Pull request merged**
