### PR TITLE
adding appveyor.yaml for version

### PR DESCRIPTION
**Pull request by brendankowitz**
* Adds appveyor.yaml for version
* Removes old nuspec

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
How would packaging work on Appveyor after this PR gets merged? Will it still rely on other projects copying outputs into `Caliburn.Micro.Autofac.Packaging\lib`?
That would be helpful to understand if [this commit](https://github.com/brendankowitz/Caliburn.Micro.Autofac/pull/8/commits/59a5e158463471d55b334c936c42dd1ac28f55ab) in PR #8 is ok or not.

**Comment by brendankowitz** [comment]
The nuspec being deleted looks unused. The Packaging dir still exists and is the same. Currently copying the package output is still required

**Comment by BrainCrumbz** [comment]
Ok, so will have to revert back that part. Thanks.

**Comment by BrainCrumbz** [comment]
~~On a similar topic, in repository root there's a `Caliburn.Micro.Autofac.nuspec` file, 5 years old. Should also this one be deleted?~~
Please ignore, just found out this PR is doing exactly that.

**Comment by BrainCrumbz** [comment]
From a rough look, it seems like this is now failing because NuGet restore has been disabled. [This](https://www.appveyor.com/blog/2014/03/18/about-nuget-package-restore/) AppVeyor blog post (_Command-line package restore_ section) suggests to add a pre-build command, that in this project case should be similar to:

``` yaml
before_build:
  - nuget restore src\Caliburn.Micro.Autofac.sln
```

**Pull request merged**
