### PR TITLE
chore(deps): update WPF to Caliburn.Micro 3.0.1

### PR DESCRIPTION
**Pull request by BrainCrumbz**
NOTE: could not update other platforms, we don't have them available at the moment

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
@brendankowitz Regarding this pending PR and another one ( #2 ), would you consider adding someone as a contributor, so to look after those?

Thank you

(Apologies for crossposting with Twitter, not sure how we can get in contact with you)

**Comment by brendankowitz** [comment]
Thanks for the PR, since this nuget contains autofac integration for a number of platforms we should have a consistent package.

I will add you as a collaborator as it would be good to get everything up to date

**Comment by BrainCrumbz** [comment]
Thanks for adding me/my team. 

Only issue with this particular change was that on dev machine I could not open Windows Phone related projects, no WP8 SDK installed. 
Let me see how it goes as soon as I manage to download & install SDK.

**Comment by brendankowitz** [comment]
Perhaps it would be better to just remove the WP8 project. I would be ok this since WP10 is released.

**Comment by BrainCrumbz** [comment]
I see (and that would be an easy start with project 😺 ). So looking at current projects:
1. Caliburn.Micro.Autofac.Packaging
2. Caliburn.Micro.Autofac.UniversalApps
3. Caliburn.Micro.Autofac.WinPhoneUniversal
4. Caliburn.Micro.Autofac.WP8
5. Caliburn.Micro.Autofac.WPF
6. samples\Sample-Win81
7. samples\Sample-WP7
8. samples\Sample-WP81
9. samples\Sample-WPF

are you suggesting to remove the following WP7/ WP8/ WP81 related ones:
1. Caliburn.Micro.Autofac.WP8
2. samples\Sample-WP7
3. samples\Sample-WP81

while keeping these:
1. Caliburn.Micro.Autofac.Packaging
2. Caliburn.Micro.Autofac.UniversalApps
3. Caliburn.Micro.Autofac.WinPhoneUniversal
4. Caliburn.Micro.Autofac.WPF
5. samples\Sample-Win81
6. samples\Sample-WPF

@brendankowitz ?

**Comment by BrainCrumbz** [comment]
Please, regarding removing WP8 projects, have a look at PR #3

**Comment by BrainCrumbz** [comment]
Closing this PR as related work is happening now on branch [caliburn-micro-3.0.1](https://github.com/brendankowitz/Caliburn.Micro.Autofac/tree/chore/caliburn-micro-3.0.1)

**Pull request closed without merging**
